### PR TITLE
Subresource Integrity: added n:integrity

### PR DESCRIPTION
**Pull request by dg**
https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

### CODE REVIEW

**Comment by vojtech-dobes** [comment]
What if content of the file gets fetched when it's already compromised? Integrity than won't complain, which is wrong - at least if I understand Subresource integrity and this PR correctly.

**Comment by Unlink** [comment]
Maybe it can have optional parameter with path or url to file to calculate hash.
So i can keep verified content locally to calculate hash (or use another CDN for calculation) and serve it from CDN.

**Comment by f3l1x** [comment]
:+1:

**Comment by lookyman** [comment]
"I'm gonna verify the integrity of this downloaded file by.. downloading it? Sure, that will work great!".

As @vojtech-dobes said, isn't this completely broken?

**Comment by fprochazka** [comment]
I don't like it either, you should be able to provide filepath in local filesystem, or stream to read from.

**Comment by dg** [comment]
IMHO attribute `integrity` should be part of documentation like here http://www.bootstrapcdn.com/ (click on arrow).

**Pull request closed without merging**
