### PR TITLE
CachingIterator: do not ask when not in valid state

### PR DESCRIPTION
**Pull request by hrach**
- bug fix: yes
- BC break: no, [but...](https://xkcd.com/1172/)
- doc PR: no

The inner iterator is one iteration ahead and therefore when CachingIterator asks for the next value (key), it uses a current() method on the inner iterator. But the iteration may have finished and calling iterator's current() and key() in invalid state may produce an exception or invalid data.

PHP'S internal ArrayIterator returns a null, but generally speaking the iterators should rather throw. When doing types properly, we [can't even type such interface](https://phpstan.org/r/9857a2bd-bd79-4152-b1a8-ee336733ed15).

This PR asks first if the inner iterator is in a valid state.

### CODE REVIEW

**Comment by hrach** [comment]
Test failures seems unrelated.

**Comment by hrach** [comment]
@dg what do you think?

**Comment by dg** [comment]
Seems legit.

**Comment by hrach** [comment]
Thank you :)

**Pull request merged**
