### PR TITLE
Compiler: <script> with type text/json is escaped as javascript

### PR DESCRIPTION
**Pull request by kukulich**

### CODE REVIEW

**Comment by JanTvrdik** [comment]
JSON mime type is `application/json`. Why do you need `text/json`?

**Comment by kukulich** [comment]
Force pushed with `application/json`, however it doesn't matter if there's `application/json` or `text/json`. Both work with this pull request.

**Comment by dg** [comment]
Can you prepend commit with `Compiler:`, ie. `Compiler: text/json is escaped as javascript`?

**Comment by kukulich** [comment]
@dg Done

**Comment by dg** [comment]
Thanks

**Pull request merged**
