### PR TITLE
Parser: fixed syntax=off

### PR DESCRIPTION
**Pull request by matej21**
fixes http://forum.nette.org/cs/22145-makro-n-syntax-off-sa-vypne-skor-ako-by-malo
#drunkPR

### CODE REVIEW

**Comment by dg** [comment]
Heh, I just fixed it too ;)

**Comment by matej21** [comment]
I was first! :D

**Comment by dg** [comment]
Not only the first, but your solution is better than my.

**Comment by dg** [comment]
Please change Lvl to Level, short names are démodé https://github.com/nette/bootstrap/commit/6ef8507bccdd3ebe0fdd2aefed17a3ea53015a62

**Comment by matej21** [comment]
fixed

**Comment by dg** [comment]
Thx!

**Pull request merged**
