### PR TITLE
Filters: few BC breaks to consider

### PR DESCRIPTION
**Pull request by JanTvrdik**

### CODE REVIEW

**Comment by fprochazka** [comment]
Case sensitivity is a nasty one. However, it can be really easily fixed.

**Comment by dg** [comment]
The need to receive arguments as array will disappear with PHP 5.6, so it is imho unnecessary.

**Comment by JanTvrdik** [comment]
Yes, with PHP 5.6+ it is a lot easier to write "filter loader". The proposed solution makes it easy to write "filter loader" in older versions and removes the useless `array_unshift`.

**Comment by dg** [comment]
Case sensitivity for Latte filters is really nasty, BC break for dynamic filters too.

**Pull request closed without merging**
